---
- name: Deploy YC infra
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy YC infra with terraform
      terraform:
        force_init: true
        project_path: ../../terraform
        state: "{{ tf_state }}"
        backend_config:
          endpoint  : "storage.yandexcloud.net"
          bucket    : "{{ tf_bucket_name }}"
          region    : "us-east-1"
          key       : "{{ tf_bucket_state_file_name }}"
          access_key: "{{ tf_bucket_access_key }}"
          secret_key: "{{ tf_bucket_secret_key }}"
          skip_region_validation     : "true"
          skip_credentials_validation: "true"
    - meta: refresh_inventory

- name: Deploy python docker modules
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait connection
      wait_for_connection:
    - name: Gather facts
      setup:
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: true
    - name: Install python modules docker and docker-compose
      pip:
        name: 
          - docker
          - docker-compose

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users: ubuntu

- name: Deploy gitlab-ci
  hosts: gitlab_hosts
  become: true

  roles:
    - role: gitlab-ci

- name: Deploy monitoring
  hosts: monitoring_hosts
  become: true

  tasks:
    - name: Deploy monitoring system (Prome and Grafana)
      include_tasks: monitoring.yml
